window_size = 100
window_overlap = 0.5
sampling_freq = 2000
normalization = "None"
fs = 0
lowcut = 20
highcut = 450
filter_order = 4
wamp_threshold = 2e-9
features = [ "mav", "wl", "wamp", "mavs",]
model_path = "model/GRU_DB4_restimulus/GRU_DB4_restimulus.tflite"
log_path = "model/GRU_DB4_restimulus/output/inference.csv"
model_states = [ 0, 1, 2, 3,]
input_file_path = "data/DB4_restimulus/test_data.pkl"
