window_size = 50
window_overlap = 0.9
sampling_freq = 2000
normalization = "None"
fs = 0
lowcut = 20
highcut = 450
filter_order = 4
wamp_threshold = 0.2
features = [ "mav", "wl", "wamp", "mavs",]
model_path = "model/GRU_DB4_stimulus/GRU_DB4_stimulus.tflite"
log_path = "model/GRU_DB4_stimulus/output/inference.csv"
model_states = [ 0, 1, 2, 3,]
input_file_path = "data/DB4_stimulus/test_data.pkl"
