window_size = 400
window_overlap = 0.25
sampling_freq = 2000
normalization = "None"
fs = 0
lowcut = 20
highcut = 450
filter_order = 4
wamp_threshold = 2e-9
features = [ "mav", "wl", "wamp", "mavs",]
model_path = "model/LSTM_DB4_restimulus_all/LSTM_DB4_restimulus_all.tflite"
log_path = "model/LSTM_DB4_restimulus_all/output/inference.csv"
model_states = [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,]
input_file_path = "data/DB4_restimulus_all/test_data.pkl"
