window_size = 400
window_overlap = 0.25
sampling_freq = 2000
normalization = "None"
fs = 0
lowcut = 20
highcut = 450
filter_order = 4
wamp_threshold = 2e-8
features = [ "mav", "wl", "wamp", "mavs",]
model_path = "model/LSTM_DB4_rerepetition/LSTM_DB4_rerepetition.tflite"
log_path = "model/LSTM_DB4_rerepetition/output/inference.csv"
model_states = [ 1, 2, 3,]
input_file_path = "data/DB4_rerepetition/test_data.pkl"
