window_size = 400
window_overlap = 0.5
sampling_freq = 2000
normalization = "None"
fs = 0
lowcut = 20
highcut = 450
filter_order = 4
wamp_threshold = 0.02
features = [ "mav", "wl", "wamp", "mavs",]
model_path = "model/LSTM_DB4_repetition_allstates/LSTM_DB4_repetition_allstates.tflite"
log_path = "model/LSTM_DB4_repetition_allstates/output/inference.csv"
model_states = [ 0, 1, 2, 3, 4, 5, 6,]
input_file_path = "data/DB4_repetition_allstates/test_data.pkl"
